      DOUBLE PRECISION FUNCTION DCL1(Z)
      DOUBLE COMPLEX Z
C
C     *** PURPOSE:
C
C     DCL1 IS A DOUBLE PRECISION FUNCTION SUBPROGRAM WHICH RETURNS THE
C     L1-TYPE MAGNITUDE OF A COMPLEX NUMBER Z, I.E., THE NUMBER
C     DABS(RE(Z))+DABS(IM(Z))  WHERE RE(Z) AND IM(Z) ARE THE REAL AND
C     IMAGINARY PARTS, RESPECTIVELY, OF Z.
C
C     THIS VERSION DATED MAY 1980.
C     ALAN J. LAUB, UNIVERSITY OF SOUTHERN CALIFORNIA.
C
C     INTERNAL VARIABLES:
C
      DOUBLE COMPLEX ZDUM
C
C     FORTRAN FUNCTIONS CALLED:
C
      DOUBLE PRECISION DABS
C
C     INTERNAL FUNCTIONS:
C
      DOUBLE PRECISION DIMAG,DREAL
      DREAL(ZDUM) = ZDUM
      DIMAG(ZDUM) = (0.0D0,-1.0D0)*ZDUM
C
      DCL1 = DABS(DREAL(Z))+DABS(DIMAG(Z))
      RETURN
      END
